### ISSUE TITLE
Bug / improvement; create new page doesnt fill associated translation

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/jekyllpro-cms#37]
Listing potential bugs / improvements:

- [ ] create page in english, fill the fields, save the page - keep the same page and don't refresh - then click on `translate to`; the title gets created but the content is empty (nothing get cloned). If you refresh the english page then re-click on translate it will however work.
- [ ] translatable enums; (e.g. `section` in `1912pike`) - it'd be great to have those parts automatically translated - allowing to not have to select the chinese version - nor have to have both english and chinese in the list
- [ ] translatable UI - we rely on UiFormat: `ui:help` to display hints / helps to the various fields - but it's one language only

/cc @woodpig07

**Comment by JuhaS** [comment]
@haishanh feel free to create separate implementation issues

**Comment by woodpig07** [comment]
not relevant anymore
