### ISSUE TITLE
default folder for image update

### ISSUE THREAD

**Issue by haishanh** [Wiredcraft/jekyllpro-cms#59]
Follow discussion with @hunvreus 

Currently while you open the upload image modal, it displays the root level file structure of the repo, and your image will be uploaded to the root folder. You have to choose the destination folder manually.

Maybe we should set a default image upload folder for a collection. 

For example, for `posts` we default the upload folder to `images/posts`, for `article` we default to `images/article`

**Comment by hunvreus** [comment]
Actually I'd like to be able to set it in the schema.

**Comment by woodpig07** [comment]
This was done in PR #72 
You can specify the default upload folder(`"ui:options": {"file_dir": "<folder_path_here>"}`) in schema file, for example
```
...
"uiSchema": {
 "body": {
   "ui:widget": "customCodeMirror",
   "ui:help": "Description of the product",
   "ui:options": {
     "file_dir": "images/products"
   }
 },
```
