### ISSUE TITLE
Prompt when uploading a file with the same name

### ISSUE THREAD

**Issue by samcheah** [Wiredcraft/jekyllpro-cms#60]
A lot of the images on the current website are badly named (not descriptive, wrong formatting, using special characters etc.), so I have been renaming them as I upload.

However, I have doubled up on names accidentally while doing this, and not realised until I saw the wrong image in a post or article.

Can we please implement a prompt when you are going to overwrite a file due to the same file name?

**Comment by woodpig07** [comment]
not relevant anymore
