### ISSUE TITLE
Cannot save FAQ entries

### ISSUE THREAD

**Issue by samcheah** [Wiredcraft/jekyllpro-cms#62]
I get the error message `Unable to complete the operation` whenever I try to save an FAQ entry. Tried in both English and Chinese - same error message.

@woodpig07 @haishanh

**Comment by woodpig07** [comment]
Probably schema issue, as it did not define the folder to save FAQ files.
https://github.com/starbucks-china/starbucks-website/blob/master/_schemas/faq.json
Let me update it

**Comment by woodpig07** [comment]
done, please try again @samcheah

**Comment by samcheah** [comment]
Confirmed working now - thanks @woodpig07 

Closing this issue.
