### ISSUE TITLE
Jekyllpro suggestions

### ISSUE THREAD

**Issue by fuzhuang** [Wiredcraft/jekyllpro-cms#65]
1. We need better structuring of pages, with subpages and language distinction
2. Inside page edit; add the actual site URL
3. How to adjust the URL/slug? Permalink?
4. Add an expand in the editing text box
5. Add a page preview option
6. How to set meta tags?
    > We have `Keywords (SEO)` and `Description (SEO)` fields which can be edited to generate the keywords and description meta tag in html head.
7. As switching branches can take up quite some time, can we have a loading progress bar
    > That's because the "content list" index is not generated beforehand. It will only be triggered after someone switch to this branch. And the first generation indeed takes quite some time. But if someone switched to this branch before, others who switch to this branch does not need to wait for a long time to see the content. Also, we just did an optimization on the index generation, now only the first generation takes quite some time, future generations are done incrementally. 
8. After upload image file, don’t know where it went so I can’t select it. 
9. How to create a new branch?
    > This can not be done on the CMS UI for now. You have to use a git tool to do that.
10. I saved a change on a page in master branch. Did not see change on staging site. how to deploy?
    > JekyllPro will deploy the site automatically, with the repo going big there might be delay before your modification being live. 
11. If changes are made on the page and I click Back without saving, it doesn’t warn me
    > Could add a prompt to user before losing changes.
12. Looking at the Contact Us page and many other pages, that’s all HTML in the Body input. I thought it would be fields to update. 
    > This is not JekyllPro related; we can define a form for us to fill in the info, in this case we preferred to use a regular HTML page as these are not collections of content. That's just a preference and could be changed, but I don't think we should.
13. For a page like Responsibility, where to define the connected pages under it? It’s not in the CMS.
    > Right now we are automating this by listing all the latest responsibility related articles. Again, we can configure it another way so that you can select specific pages.
14. What is the Categories for?
    > It will be part of the permalink and helps us structure the pages.
15. If I created a new page, how to define where it’s going to live?
    > We have default rules for how we build the permalink (using categories and the title), but you can override it with the `permalink` attribute. We don't recommend doing this (as it does impact the rules we've built for the navigation panel), but we could simply add a field for you to change this.
16. Could we have a versioning of pages?
    > It's all versioned in GitHub.

**Comment by woodpig07** [comment]
not relevant anymore
